### ISSUE TITLE
Branded notebook in MyBinder

### ISSUE THREAD

**Issue by psychemedia** [mmh352/metadata-tutorial-container#1]
You can brand the notebook too by [adding assets to `.jupyter` folder](https://github.com/innovationOUtside/tm129-robotics2020/blob/2ecbf8e71bdd9b9a01b8d4346548fd36c4dac932/.jupyter/custom/custom.css#L19).

**Comment by mmh352** [comment]
I assume this is something that the repo2docker script sorts out, so that they are placed in the correct location?

**Comment by psychemedia** [comment]
`repo2docker` launches from the top level of the directory the repo contents are placed in, and the `.jupyter` directory is on the path the notebook server looks to fo config files.

**Comment by mmh352** [comment]
Very interesting and I'll note that for future cases. For the metadata tutorial the branding is provided by the wrapping tutorial interface, so I'll close this for the time being.
